export const config = {
    URN_PREFIX: "urn:adobe:aue:",
    META_SELECTOR: "meta[name^='urn:adobe:aue:']",
    META_NAMESPACE: "meta[name='urn:adobe:aue:config:namespace']",
    USER_INPUT_RELAY_MESSAGE: "REMOTE_APP_USER_INPUT",
    DEFAULT_PREFIX: "data-aue-",
    COMPONENT_ITEM_TYPE: "component",
    RTE_URL: "https://cdn.experience.adobe.net/solutions/CQ-aem-headless-rte/assets/tinymce-684/js/tinymce/tinymce.min.js",
    EVENT_APP_INITIALIZED: "aue:initialized",
    EVENT_UI_SELECT: "aue:ui-select",
    EVENT_UI_PREVIEW: "aue:ui-preview",
    EVENT_UI_EDIT: "aue:ui-edit",
    EVENT_CONTENT_MOVE: "aue:content-move",
    EVENT_CONTENT_ADD: "aue:content-add",
    EVENT_CONTENT_COPY: "aue:content-copy",
    EVENT_CONTENT_PATCH: "aue:content-patch",
    EVENT_CONTENT_REMOVE: "aue:content-remove",
    EVENT_CONTENT_UPDATE: "aue:content-update",
};
